spring:
  data:
    mongodb:
      database: kitchensink
      port: 27017
      host: localhost
      authentication-database: admin
      username: admin
      password: password

server:
  port : 8080
  servlet:
    context-path: /kitchensink
